language: objective-c
osx_image: xcode10.3
script:
    - xcodebuild clean test -project HTTPKit.xcodeproj -scheme HTTPKit -destination "platform=iOS Simulator,name=iPhone X,OS=12.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
