language: swift
script:
  swift package generate-xcodeproj
  xcodebuild test \
          -scheme HTTPKit \
          -destination platform="macOS" \
          --enable-code-coverage \
          -derivedDataPath .build/derivedData

